{% set name = "pcsclite" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pcsclite.apdu.fr/files/pcsc-lite-{{ version }}.tar.bz2
  sha256: d6c3e2b64510e5ed6fcd3323febf2cc2a8e5fda5a6588c7671f2d77f9f189356

build:
  skip: true  # [not linux]
  script:
    - set -e
    - set -x
    - if test -f Makefile; then make distclean; fi
    - rm -rf *.cache *.m4 config.guess config.log config.status config.sub depcomp ltmain.sh
    - autoreconf --verbose --install --force
    - ./configure --prefix=$PREFIX --sbindir=$PREFIX/bin
    - make install
    - make distcheck
    - rm $PREFIX/bin/pcsc-spy
    - rm $PREFIX/lib/libpcscspy.so*
  number: 1
  run_exports:
    - {{ pin_subpackage('pcsclite', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf-archive
    - automake
    - flex
    - libtool
    - make
    - pkg-config
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libudev
    - libsystemd                None
  run:

test:
  commands:
    - pcscd --version
    - test -f $PREFIX/include/PCSC/pcsclite.h
    # Test specific SO versions to prevent future package ABI breaks
    - test -f $PREFIX/lib/libpcsclite.so.1
    - test -f $PREFIX/lib/pkgconfig/libpcsclite.pc


about:
  home: https://pcsclite.apdu.fr/
  dev_url: https://salsa.debian.org/rousseau/PCSC
  summary: Middleware to access a smart card using SCard API (PC/SC).
  license: BSD-3-Clause and GPL-3.0-or-later and BSD-2-Clause and MIT
  license_file:
    - COPYING
    - GPL-3.0.txt

extra:
  recipe-maintainers:
    - leofang
    - thewchan
